####################################################################################################
# Access Control List for Messager Queue Server
####################################################################################################

---
can_read:
  - 127.0.0.1
  - 3.3.3.3
  - 144.56.77.92

can_write:
  - 127.0.0.1
  - 129.2.2.3
  - 144.56.77.92

can_admin:
  - 127.0.0.1
  - 129.2.2.3
  - 144.56.77.92
