####################################################################################################
# Access Control List for Messager Queue Server
####################################################################################################

---
can_read:
  - 127.0.0.1
  - 3.3.3.3

can_write:
  - 127.0.0.1
  - 80.87.25.216
  - 78.47.70.178

can_admin:
  - 127.0.0.1
  - 80.87.25.216

